name: EC2 로 배포하기

on:
  push:
    branches:
      - main

jobs:
  Auto-Deploy-Job:
    runs-on: ubuntu-latest

    steps:
      - name: Github Repository 의 파일 가져오기
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml 파일 생성
        run: |
          echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml

      - name: 빌드하기
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
          
          
          

      - name: 빌드된 파일 이름 변경하기
        run: |
          cd ./build/libs
          ls
          mv *AWS_CICD.jar ./app.jar

      - name: SCP로 EC2에 jar 파일 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "./app.jar"
          target: "~/project/tobe/"

#      - name: SSH로 EC2에 접속하기
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ${{ secrets.EC2_USERNAME }}
#          key: ${{ secrets.EC2_PRIVATE_KEY }}
#          script_stop: true
#          script: |
#            rm -rf /home/ubuntu/project-server/cur
#            mkdir /home/ubuntu/project-server/cur
#            mv /home/ubuntu/project-server/tobe/project.jar /home/ubuntu/project-server/cur/project.jar
#            cd /home/ubuntu/project-server/cur
#            sudo fuser -k -n tcp 8080 || true
#            sudo nohup java -jar project.jar > ./output.log 2>&1 &
#            rm -rf /home/ubuntu/project-/tobe